logging:
  level:
    org:
      springframework:
        cloud:
          task=DEBUG
                           
spring:
  application:
    name=springcloudtaskbatchTestApplication
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  batch:
    initialize-schema: always
maven:
  remoteRepositories:
    springRepo:
      url: https://repo.spring.io/libs-snapshot